### ISSUE TITLE
avatto_me167 and IoBroker

### ISSUE THREAD

**Issue by mucke1985** [twhittock/avatto_me167#6]
Hello I use the converter in IoBroker everything that is sent to the thermostat works great.

Unfortunately, the received data is not written to the data points in IoBroker

Or do I have to adjust something in the converter for the IoBroker

below some packets received

`{"type":"commandDataReport","data":{"seq":28160,"dpValues":[{"dp":4,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,220]}}]},"linkquality":87,"groupID":0,"cluster":"manuSpecificTuya","meta":{"zclTransactionSequenceNumber":46,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

{"type":"commandDataReport","data":{"seq":29952,"dpValues":[{"dp":5,"datatype":2,"data":{"type":"Buffer","data":[0,0,1,14]}}]},"linkquality":94,"groupID":0,"cluster":"manuSpecificTuya","meta":{"zclTransactionSequenceNumber":53,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

{"type":"commandDataReport","data":{"seq":36096,"dpValues":[{"dp":4,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,240]}}]},"linkquality":54,"groupID":0,"cluster":"manuSpecificTuya","meta":{"zclTransactionSequenceNumber":77,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}

{"type":"commandDataReport","data":{"seq":40960,"dpValues":[{"dp":5,"datatype":2,"data":{"type":"Buffer","data":[0,0,1,14]}}]},"linkquality":87,"groupID":0,"cluster":"manuSpecificTuya","meta":{"zclTransactionSequenceNumber":96,"manufacturerCode":null,"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}},"endpoint_id":1}`

**Comment by twhittock** [comment]
Sorry I've no idea - the temperature response works ok in z2m & home assistant, so I guess there's some aspect to the iobroker configuration - I'm not familiar with the software so I can't help there.

**Comment by mucke1985** [comment]
OK thank you for the info

I've solved the problem in the meantime

should someone read the entry here who has the same problem

create the file me167.js directly in the folder /devices and not as a converter then simply restart the converter

**Comment by Paalap** [comment]
Hi, I'm also using it on iobroker and getting the error message regarding the weekly schedule (overall it is working good)

Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')

I do not understand why it is appering... hasOwnProperty shoudl not create any issues on typerror.


Thank you in advance

**Comment by twhittock** [comment]
@Paalap I don't really understand that - the only time we use `hasOwnProperty` in the code here is to access the state from the object in the metadata. In this case, the metadata must have had a `state` member which was undefined. It's not clear how that could happen, since the state contains all the information about the current state of the device... Perhaps it needs to wait a while to fill in some more parts of the state object before the weekly schedule can be read from zigbee...? Very unusual.

**Comment by Paalap** [comment]
Here an example what is happing on connection (log info moved before haswonproperty call)


```
zigbee.0
2022-12-03 17:56:32.987	info	zigbee-herdsman-converters:me167_thermostat: BattOK - Error Code: {"dp":35,"datatype":5,"data":{"type":"Buffer","data":[0]}}

zigbee.0
2022-12-03 17:56:32.872	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:135:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:32.870	info	{"received day":6,"received values":{"type":"Buffer","data":[7,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:32.722	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:132:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:32.721	info	{"received day":5,"received values":{"type":"Buffer","data":[6,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:32.594	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:129:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:32.593	info	{"received day":4,"received values":{"type":"Buffer","data":[5,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:32.467	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:126:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:32.466	info	{"received day":3,"received values":{"type":"Buffer","data":[4,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:21.968	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:123:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:21.967	info	{"received day":2,"received values":{"type":"Buffer","data":[3,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:21.846	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:120:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:21.845	info	{"received day":1,"received values":{"type":"Buffer","data":[2,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}

zigbee.0
2022-12-03 17:56:21.695	error	Error collectOptions for 84ba20fffee087f9. Error: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty') at weeklySchedule (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:49:44) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/me167.js:117:15) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:464:43 at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:181:23)

zigbee.0
2022-12-03 17:56:21.693	info	{"received day":0,"received values":{"type":"Buffer","data":[1,6,0,0,120,8,0,0,160,18,0,0,220,20,0,0,200]}}
```
